
CREATE PROCEDURE GENERATE_CATEGORIES (@CATEGORIES_COUNT INT) --DROP PROCEDURE GENERATE_CATEGORIES;
AS
DECLARE @i INT = 1;
BEGIN
    WHILE @i <= @CATEGORIES_COUNT
    BEGIN
		INSERT INTO [SHOP].[CATEGORIES] ([NAME]) VALUES (CONCAT('Category ', @i));
		SET @i = @i + 1;
    END
END;

