CREATE PROCEDURE [GENERATE_PRODUCTS] (@CATEGORIES_COUNT INT, @PRODUCTS_COUNT INT) --DROP PROCEDURE GENERATE_PRODUCTS;
AS
DECLARE @i INT = 1;
BEGIN
    WHILE @i <= @PRODUCTS_COUNT
    BEGIN
		INSERT INTO [SHOP].[PRODUCTS] ([CATEGORY_ID], [NAME]) VALUES ((ABS(CHECKSUM(NEWID())) % @CATEGORIES_COUNT) + 1 , CONCAT('Product ', @i));
		SET @i = @i + 1;
    END
END;