CREATE TABLE [SHOP].[CATEGORIES] (
    [ID]   INT           IDENTITY (1, 1) NOT NULL,
    [NAME] NVARCHAR (50) NOT NULL,
    CONSTRAINT [CATEGORIES_PK] PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([NAME] ASC)
);

