CREATE TABLE [SHOP].[PRODUCTS] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [CATEGORY_ID] INT           NOT NULL,
    [NAME]        NVARCHAR (50) NOT NULL,
    [PRICE]       MONEY         NULL,
    CONSTRAINT [PRODUCTS_PK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PRODUCTS_CATEGORIES_FK] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [SHOP].[CATEGORIES] ([ID]),
    UNIQUE NONCLUSTERED ([NAME] ASC)
);

