USE [ZLOBIN];

GO

CREATE SCHEMA [SHOP];

GO

CREATE TABLE [SHOP].[CATEGORIES] (
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(50) UNIQUE NOT NULL,

	CONSTRAINT [CATEGORIES_PK] PRIMARY KEY ([ID])
);

GO

CREATE PROCEDURE [GENERATE_CATEGORIES] (@CATEGORIES_COUNT INT) --DROP PROCEDURE GENERATE_CATEGORIES;
AS
DECLARE @i INT = 1;
BEGIN
    WHILE @i <= @CATEGORIES_COUNT
    BEGIN
		INSERT INTO [SHOP].[CATEGORIES] ([NAME]) VALUES (CONCAT('Category ', @i));
		SET @i = @i + 1;
    END
END;

GO

EXEC [GENERATE_CATEGORIES] @CATEGORIES_COUNT = 10;

GO

CREATE TABLE [SHOP].[PRODUCTS] (
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[CATEGORY_ID] INT NOT NULL,
	[NAME] NVARCHAR(50) UNIQUE NOT NULL,
	[PRICE]	MONEY NULL

	CONSTRAINT [PRODUCTS_PK] PRIMARY KEY ([ID]),
	CONSTRAINT [PRODUCTS_CATEGORIES_FK] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [SHOP].[CATEGORIES] ([ID])
);

GO

CREATE PROCEDURE [GENERATE_PRODUCTS] (@CATEGORIES_COUNT INT, @PRODUCTS_COUNT INT) --DROP PROCEDURE GENERATE_PRODUCTS;
AS
DECLARE @i INT = 1;
BEGIN
    WHILE @i <= @PRODUCTS_COUNT
    BEGIN
		INSERT INTO [SHOP].[PRODUCTS] ([CATEGORY_ID], [NAME]) VALUES ((ABS(CHECKSUM(NEWID())) % @CATEGORIES_COUNT) + 1 , CONCAT('Product ', @i));
		SET @i = @i + 1;
    END
END;

GO

EXEC [GENERATE_PRODUCTS] @CATEGORIES_COUNT = 10, @PRODUCTS_COUNT = 150;

GO

SELECT * FROM [SHOP].[CATEGORIES];
SELECT * FROM [SHOP].[PRODUCTS] ORDER BY [NAME];